apiVersion: v1
kind: Service
metadata:
  name: triton-unified-svc
spec:
  ports:
  - port: 8000
    name: http
    targetPort: 8000
  - port: 8002
    name: metrics
    targetPort: 8002
  selector:
    shared-app: triton-inference
