apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: triton-unified-healthcheck
  namespace: default
spec:
  default:
    config:
      httpHealthCheck:
        port: 8000
        requestPath: /v2/health/ready
      type: HTTP
  targetRef:
    group: ""
    kind: Service
    name: triton-unified-svc
