apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: triton-l4-healthcheck
  namespace: default
spec:
  default:
    config:
      httpHealthCheck:
        port: 8000
        requestPath: /v2/health/ready
      type: HTTP
  targetRef:
    group: inference.networking.x-k8s.io
    kind: InferencePool
    name: triton-l4-pool
---
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: triton-g4-healthcheck
  namespace: default
spec:
  default:
    config:
      httpHealthCheck:
        port: 8000
        requestPath: /v2/health/ready
      type: HTTP
  targetRef:
    group: inference.networking.x-k8s.io
    kind: InferencePool
    name: triton-g4-pool
