apiVersion: networking.gke.io/v1
kind: GCPBackendPolicy
metadata:
  name: triton-ubb-policy
  namespace: default
spec:
  default:
    balancingMode: CUSTOM_METRICS
    customMetrics:
    - name: gke.gpu_duty_cycle
      maxUtilizationPercent: 80
      dryRun: false
  targetRef:
    group: ""
    kind: Service
    name: triton-unified-svc
